# Generated by Django 4.2.7 on 2025-10-12 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Название партнера, например "Кофейня на Арбате"',
                        max_length=200,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email для связи",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Телефон для связи",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("vip", "VIP"),
                        ],
                        help_text="Тариф партнера",
                        max_length=10,
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ежемесячная плата в рублях",
                        max_digits=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("paused", "Приостановлен"),
                            ("suspended", "Заблокирован"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "total_impressions",
                    models.IntegerField(
                        default=0,
                        help_text="Общее количество показов точек партнера в маршрутах",
                    ),
                ),
                (
                    "impressions_this_month",
                    models.IntegerField(default=0, help_text="Показы за текущий месяц"),
                ),
                (
                    "last_impression_date",
                    models.DateTimeField(
                        blank=True, help_text="Дата последнего показа", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата регистрации партнера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
                "db_table": "partners",
            },
        ),
    ]
