# Generated by Django 4.2.7 on 2025-10-12 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="emoji",
        ),
        migrations.RemoveField(
            model_name="mood",
            name="emoji",
        ),
    ]
