# Generated by Django 4.2.7 on 2025-10-12 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_remove_interest_emoji_remove_mood_emoji"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="osm_area_id",
        ),
        migrations.RemoveField(
            model_name="cityarea",
            name="osm_area_id",
        ),
    ]
