# Generated by Django 4.2.7 on 2025-10-13 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routes", "0003_remove_city_osm_area_id_remove_cityarea_osm_area_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="comment",
            field=models.TextField(blank=True, help_text="Текстовый отзыв", null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Оценка маршрута (1–5)", null=True
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="going",
            field=models.BooleanField(
                default=False, help_text="Планирует ли пользователь идти по маршруту"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="routes.route",
            ),
        ),
    ]
