# Generated by Django 4.2.7 on 2025-10-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0004_feedback_comment_feedback_rating_feedback_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="routes.city",
            ),
        ),
    ]
