# Generated by Django 4.2.7 on 2025-10-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0005_route_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="point",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Район точки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.cityarea",
            ),
        ),
    ]
