# Generated by Django 4.2.7 on 2025-10-15 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0006_point_address_point_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="session_id",
        ),
    ]
