# Generated by Django 5.0.14 on 2025-11-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0007_remove_feedback_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestCategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Идентификатор категории",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Название категории", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Категория интереса",
                "verbose_name_plural": "Категории интересов",
                "db_table": "interest_categories",
            },
        ),
        migrations.AddField(
            model_name="interest",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Категория интереса",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="routes.interestcategory",
            ),
        ),
    ]
