# Generated by Django 5.0.14 on 2025-11-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0008_interestcategory_interest_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название тега (например, 'romantic')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание тега для эмбеддингов", null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("interest", "Интерес"),
                            ("mood", "Настроение"),
                            ("type", "Тип места"),
                            ("feature", "Особенность"),
                        ],
                        help_text="Категория тега",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="point",
            name="tags",
        ),
        migrations.AddField(
            model_name="point",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="points", to="routes.tag"
            ),
        ),
    ]
