# Generated by Django 5.0.14 on 2025-11-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0009_tag_remove_point_tags_point_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
