# Generated by Django 5.0.14 on 2025-12-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0010_alter_point_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="total_meters",
            field=models.IntegerField(
                blank=True, help_text="Общее расстояние маршрута", null=True
            ),
        ),
    ]
