# Generated by Django 5.0.14 on 2025-12-11 08:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0011_route_total_meters"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="is_seasonal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="point",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                help_text="Ключевые слова для улучшения эмбеддинга и поиска",
                null=True,
                size=None,
            ),
        ),
    ]
