# Generated by Django 5.0.14 on 2025-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0012_interest_is_seasonal_point_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="is_view",
            field=models.BooleanField(default=True),
        ),
    ]
