# Generated by Django 5.0.14 on 2025-12-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0013_interest_is_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="visit_time",
            field=models.IntegerField(default=0, help_text="время посещения в минутах"),
        ),
        migrations.AddField(
            model_name="route",
            name="walk_time",
            field=models.IntegerField(default=0, help_text="время пешком в минутах"),
        ),
    ]
