# Generated by Django 5.0.14 on 2026-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0014_route_visit_time_route_walk_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="lat0",
            field=models.DecimalField(
                decimal_places=6, default=55.766157, help_text="Широта", max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="lon0",
            field=models.DecimalField(
                decimal_places=6, default=37.617797, help_text="Широта", max_digits=9
            ),
        ),
    ]
