# Generated by Django 5.0.14 on 2026-04-08 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
        ("routes", "0017_favoritepoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Начисление фрилансеру",
                "verbose_name_plural": "Начисления фрилансерам",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="point",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="point",
            name="edit_status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик (из OSM, не заполнена)"),
                    ("assigned", "Назначена фрилансеру"),
                    ("edited", "Отредактирована, ожидает проверки"),
                    ("approved", "Проверена и опубликована"),
                    ("rejected", "Отклонена, требуется доработка"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="point",
            name="review_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="point",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="snapshot_before_edit",
            field=models.JSONField(
                blank=True,
                help_text="Сериализованные данные до редактирования (только редактируемые поля)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="routes.city",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="point",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="routes.freelancerprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="point",
            index=models.Index(
                fields=["edit_status"], name="points_edit_st_24a3bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="point",
            index=models.Index(
                fields=["assigned_to", "edit_status"], name="points_assigne_e62ca0_idx"
            ),
        ),
        migrations.AddField(
            model_name="pointearning",
            name="freelancer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earnings",
                to="routes.freelancerprofile",
            ),
        ),
        migrations.AddField(
            model_name="pointearning",
            name="point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earnings",
                to="routes.point",
            ),
        ),
    ]
