# Generated by Django 4.2.7 on 2025-10-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(help_text="Заголовок статьи", max_length=255),
                ),
                ("slug", models.SlugField(help_text="URL-идентификатор", unique=True)),
                ("content", models.TextField(help_text="Текст статьи")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="Обложка статьи",
                        null=True,
                        upload_to="articles/covers/",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (если пусто — берётся title)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True,
                        help_text="Meta description для поисковиков",
                        null=True,
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "db_table": "articles",
                "indexes": [
                    models.Index(fields=["slug"], name="articles_slug_c8b0c2_idx"),
                    models.Index(
                        fields=["created_at"], name="articles_created_82e966_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="articles_is_publ_badb53_idx"
                    ),
                ],
            },
        ),
    ]
